[workspace]
authors = ["Ram√≥n <rtrinidadac25@gmail.com>"]
channels = ["conda-forge", "pytorch"]
name = "ProyectoTSCD"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
pandas = ">=2.3.3,<3"
jupyterlab = ">=4.5.1,<5"
requests = ">=2.32.5,<3"
python-dotenv = ">=1.2.1,<2"
scikit-learn = ">=1.8.0,<2"
networkx = ">=3.6.1,<4"
matplotlib = ">=3.10.8,<4"
neo4j-python-driver = ">=6.0.3,<7"
pyvis = ">=0.3.2,<0.4"
pytorch = ">=2.9.1,<3"
cpuonly = ">=2.0,<3"
torch-geometric = ">=2.6.1,<3"
seaborn = ">=0.13.2,<0.14"
