[workspace]
authors = ["Ram√≥n <rtrinidadac25@gmail.com>"]
channels = ["conda-forge"]
name = "ProyectoTSCD"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"
pandas = ">=2.3.3,<3"
jupyterlab = ">=4.5.1,<5"
requests = ">=2.32.5,<3"
python-dotenv = ">=1.2.1,<2"
scikit-learn = ">=1.8.0,<2"
networkx = ">=3.6.1,<4"
matplotlib = ">=3.10.8,<4"
